services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900" 
    networks:
      - app-network  

  api:
    container_name: geogle-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - .:/app 
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge  
